In [1]:
dd = {'s':[('a',3),('b',2),('c',4)],
    'a':[('d',1)],
    'b':[('e',8),('f',7),('d',1)],
    'c':[('e',1),('j',3)],
    'd':[('f',1),('h',1)],
    'e':[('g',1)],
    'f':[('g',5)],
    'h':[('g',1),('f',3)],
    'j':[('e',2)],
    'g':[]}

In [1]:
s a 3
s b 2
s c 4
a d 1
b e 8
b f 7
b d 1
c e 1
c j 3
d f 1
d h 1
e g 1
f g 5
h g 1
h f 3
j e 2

SyntaxError: invalid syntax (Temp/ipykernel_11692/932232198.py, line 1)

In [23]:
lis = [('a',3),('b',2),('c',4),('e',1)]

In [24]:
def my(x):
    return x[1]

In [27]:
lis = sorted(lis,key=my)
lis

[('e', 1), ('b', 2), ('a', 3), ('c', 4)]

In [4]:
lis

[('a', 3), ('b', 2), ('c', 4), ('e', 1)]

In [5]:
new = ('c',2)

In [7]:
def build_dcit(lis):
    di  = {}

    for i in lis:
        name = i[0]
        cost = i[1]
        di[name] = cost
    return di


new[0] in build_dcit(lis)

True

In [8]:
def build_dcitt(lis):
    di  = {}

    for i in lis:

        di[i[0]] = i[1]
    return di


new[0] in build_dcitt(lis)

True

In [11]:
def build_dcitt(lis):
     
    return {i[0] :i[1] for i in lis }


new[0] in build_dcitt(lis)

True

In [31]:
for i in lis:
    
    
    if (i[0] == new [0]):
        print(i)
        if i[1]<new[1]:
            pass
        else:
            ind = lis.index(i)
            lis[ind] = new

('c', 4)

In [32]:
lis

[('a', 3), ('b', 2), ('c', 2), ('e', 1)]

In [58]:
def UCS(d,goal):
    
    q = []
    q.append(('s',0))
    explored = []
    
    while len(q)>0:

        print('Queue :  ',q)
        node = q.pop(0)
        print('child pop: ',node) # node[0] --> node name AND node[1] --> cost
        
        if node[0] not in explored:
            explored.append(node[0])
        
        if node[0] == goal:
            return explored 
        
        print('Explored: ',explored)

        child = d.get(node[0])
        print('current child: ',child)
        
        for i in child:
            print(i)
            
            cost =  i[1] + node[1]
            name = i[0]
            new = (name,cost)

            
            print('{} , parent cost ({}) + child cost ({}) = {}'.format(i,node[1],i[1],cost))
            #print('////\\\\ ',new)
            
            
            if new[0] not in explored and new[0] not in build_dcit(q):
                
                q.append(new) 
                
            
                
            elif new[0] in build_dcit(q):
                #rint('[[[[[[[[[[[[[[[duplicate]]]]]]]]]]]]]]]')

                #rint(new[0],build_dcit(q)[new[0]])

                old_data = build_dcit(q)
                old_cost = old_data[new[0]]
                old_name = new[0]
                old = (old_name,old_cost)

                #rint(old)
                #rint('NNNNNNNNNNNNNNNNNNNNNN',new , node)
                if new[1] < old[1]:
                    #rint('^^^^^^^*******%%%%%%%% in if')
                    inde = q.index(old)
                    q[inde] = new
                else:
                    pass

        
        q = sorted(q,key= my)
        #print(q)
        print(50*'*')
        
    
UCS(dd,'g')

Queue :   [('s', 0)]
child pop:  ('s', 0)
Explored:  ['s']
current child:  [('a', 3), ('b', 2), ('c', 4)]
('a', 3)
('a', 3) , parent cost (0) + child cost (3) = 3
('b', 2)
('b', 2) , parent cost (0) + child cost (2) = 2
('c', 4)
('c', 4) , parent cost (0) + child cost (4) = 4
**************************************************
Queue :   [('b', 2), ('a', 3), ('c', 4)]
child pop:  ('b', 2)
Explored:  ['s', 'b']
current child:  [('e', 8), ('f', 7), ('d', 1)]
('e', 8)
('e', 8) , parent cost (2) + child cost (8) = 10
('f', 7)
('f', 7) , parent cost (2) + child cost (7) = 9
('d', 1)
('d', 1) , parent cost (2) + child cost (1) = 3
**************************************************
Queue :   [('a', 3), ('d', 3), ('c', 4), ('f', 9), ('e', 10)]
child pop:  ('a', 3)
Explored:  ['s', 'b', 'a']
current child:  [('d', 1)]
('d', 1)
('d', 1) , parent cost (3) + child cost (1) = 4
**************************************************
Queue :   [('d', 3), ('c', 4), ('f', 9), ('e', 10)]
child pop:  ('d', 3)
Explored:  ['s', 'b', 'a', 'd']
current child:  [('f', 1), ('h', 1)]
('f', 1)
('f', 1) , parent cost (3) + child cost (1) = 4
('h', 1)
('h', 1) , parent cost (3) + child cost (1) = 4
**************************************************
Queue :   [('c', 4), ('f', 4), ('h', 4), ('e', 10)]
child pop:  ('c', 4)
Explored:  ['s', 'b', 'a', 'd', 'c']
current child:  [('e', 1), ('j', 3)]
('e', 1)
('e', 1) , parent cost (4) + child cost (1) = 5
('j', 3)
('j', 3) , parent cost (4) + child cost (3) = 7
**************************************************
Queue :   [('f', 4), ('h', 4), ('e', 5), ('j', 7)]
child pop:  ('f', 4)
Explored:  ['s', 'b', 'a', 'd', 'c', 'f']
current child:  [('g', 5)]
('g', 5)
('g', 5) , parent cost (4) + child cost (5) = 9
**************************************************
Queue :   [('h', 4), ('e', 5), ('j', 7), ('g', 9)]
child pop:  ('h', 4)
Explored:  ['s', 'b', 'a', 'd', 'c', 'f', 'h']
current child:  [('g', 1), ('f', 3)]
('g', 1)
('g', 1) , parent cost (4) + child cost (1) = 5
('f', 3)
('f', 3) , parent cost (4) + child cost (3) = 7
**************************************************
Queue :   [('e', 5), ('g', 5), ('j', 7)]
child pop:  ('e', 5)
Explored:  ['s', 'b', 'a', 'd', 'c', 'f', 'h', 'e']
current child:  [('g', 1)]
('g', 1)
('g', 1) , parent cost (5) + child cost (1) = 6
**************************************************
Queue :   [('g', 5), ('j', 7)]
child pop:  ('g', 5)

['s', 'b', 'a', 'd', 'c', 'f', 'h', 'e', 'g']

In [36]:
s = []
s.append(('S',0))
s

[('S', 0)]

In [59]:
def UCS_new(d,goal):
    
    q = []
    q.append(('s',0))
    explored = []
    
    while len(q)>0:

        print('Queue :  ',q)
        node = q.pop(0)   
        
        if node[0] not in explored:
            explored.append(node[0])
        
        if node[0] == goal:
            return explored 
        
        child = d.get(node[0])
              
        for i in child:

            cost =  i[1] + node[1]
            name = i[0]
            new = (name,cost)

            if new[0] not in explored and new[0] not in build_dcit(q):
                
                q.append(new) 

            elif new[0] in build_dcit(q):

                old_data = build_dcit(q)
                old_cost = old_data[new[0]]
                old_name = new[0]
                old = (old_name,old_cost)

                if new[1] < old[1]:

                    inde = q.index(old)
                    q[inde] = new
                else:
                    pass

        
        q = sorted(q,key= my)
        print(50*'*')
        
    
UCS_new(dd,'g')

Queue :   [('s', 0)]
**************************************************
Queue :   [('b', 2), ('a', 3), ('c', 4)]
**************************************************
Queue :   [('a', 3), ('d', 3), ('c', 4), ('f', 9), ('e', 10)]
**************************************************
Queue :   [('d', 3), ('c', 4), ('f', 9), ('e', 10)]
**************************************************
Queue :   [('c', 4), ('f', 4), ('h', 4), ('e', 10)]
**************************************************
Queue :   [('f', 4), ('h', 4), ('e', 5), ('j', 7)]
**************************************************
Queue :   [('h', 4), ('e', 5), ('j', 7), ('g', 9)]
**************************************************
Queue :   [('e', 5), ('g', 5), ('j', 7)]
**************************************************
Queue :   [('g', 5), ('j', 7)]

['s', 'b', 'a', 'd', 'c', 'f', 'h', 'e', 'g']

In [60]:
dd

{'s': [('a', 3), ('b', 2), ('c', 4)],
 'a': [('d', 1)],
 'b': [('e', 8), ('f', 7), ('d', 1)],
 'c': [('e', 1), ('j', 3)],
 'd': [('f', 1), ('h', 1)],
 'e': [('g', 1)],
 'f': [('g', 5)],
 'h': [('g', 1), ('f', 3)],
 'j': [('e', 2)],
 'g': []}

In [67]:
s a 3
s b 2
s c 4
a d 1
b e 8
b f 7
b d 1
c e 1
c j 3
d f 1
d h 1
e g 1
f g 5
h g 1
h f 3
j e 20

SyntaxError: invalid syntax (<ipython-input-67-016808558b30>, line 1)

In [70]:
import time

strat =  time.time()
UCS_new(dd,'g')
end =  time.time()
total = end-strat
total

Queue :   [('s', 0)]
**************************************************
Queue :   [('b', 2), ('a', 3), ('c', 4)]
**************************************************
Queue :   [('a', 3), ('d', 3), ('c', 4), ('f', 9), ('e', 10)]
**************************************************
Queue :   [('d', 3), ('c', 4), ('f', 9), ('e', 10)]
**************************************************
Queue :   [('c', 4), ('f', 4), ('h', 4), ('e', 10)]
**************************************************
Queue :   [('f', 4), ('h', 4), ('e', 5), ('j', 7)]
**************************************************
Queue :   [('h', 4), ('e', 5), ('j', 7), ('g', 9)]
**************************************************
Queue :   [('e', 5), ('g', 5), ('j', 7)]
**************************************************
Queue :   [('g', 5), ('j', 7)]

0.0019614696502685547

In [71]:
import random

In [ ]:
BFS
1000 , 2.3
40000 , 3.5 

4000000 , 6.2

3403490934 , 2.3

[10000,400000,]

In [ ]:
DFS
1000 , 4.3
40000 , 2.5 

4000000 , 7.2

3403490934 , 2.3

In [79]:
li = []

for i in range(1000):
    
    rand = random.randint(0,50)
    li.append(rand)
len(set(li))

51

In [76]:
list(set( random.randint(0,50000) for i in range(1000)))

[26624,
 28673,
 14338,
 47106,
 49155,
 34818,
 10246,
 2051,
 34826,
 10251,
 6154,
 6157,
 24589,
 47119,
 16400,
 4112,
 22547,
 43028,
 4117,
 45078,
 45077,
 20504,
 45075,
 47131,
 24604,
 40992,
 43042,
 2084,
 38952,
 14383,
 2097,
 24628,
 41013,
 38969,
 12346,
 38973,
 41022,
 8257,
 12357,
 43078,
 6216,
 34893,
 32846,
 4175,
 6224,
 20557,
 30799,
 36947,
 18515,
 20563,
 14420,
 14425,
 18523,
 22621,
 32864,
 14433,
 24675,
 34916,
 6246,
 22631,
 14440,
 16488,
 16486,
 47213,
 111,
 49263,
 22644,
 26741,
 16502,
 24695,
 8313,
 30842,
 14458,
 47225,
 16509,
 22650,
 4219,
 2179,
 34948,
 28805,
 2182,
 8327,
 18568,
 8332,
 8336,
 22672,
 150,
 24727,
 12441,
 22682,
 6299,
 14496,
 43169,
 2210,
 12453,
 43174,
 22695,
 14504,
 10408,
 28842,
 4265,
 14502,
 26797,
 41138,
 8371,
 24758,
 37046,
 6331,
 12475,
 4287,
 43201,
 43202,
 41155,
 4293,
 10437,
 35015,
 12489,
 14537,
 10443,
 45260,
 30925,
 37069,
 18639,
 32978,
 18642,
 37079,
 47319,
 6361,
 24791,
 35035,
 20699,
 28893,
 30949,
 43240,
 28911,
 24818,
 26867,
 24821,
 37109,
 2295,
 8441,
 14588,
 47357,
 16641,
 14594,
 35073,
 16645,
 39173,
 2313,
 39179,
 16651,
 37133,
 12557,
 4366,
 18704,
 14609,
 20752,
 33045,
 39191,
 10519,
 6423,
 24858,
 33054,
 43297,
 24866,
 49443,
 24868,
 26917,
 26916,
 18727,
 18721,
 45352,
 20769,
 49451,
 18733,
 24878,
 47406,
 18737,
 47411,
 37175,
 49464,
 28986,
 6460,
 39229,
 28990,
 43327,
 13089,
 47425,
 45377,
 24897,
 8510,
 41285,
 24905,
 16713,
 35149,
 6477,
 45392,
 33112,
 45406,
 41310,
 43361,
 33123,
 35174,
 12646,
 6510,
 10606,
 47470,
 14706,
 24946,
 33142,
 39287,
 29048,
 29050,
 24954,
 35197,
 14718,
 31104,
 49541,
 4487,
 22920,
 14729,
 31115,
 49548,
 37265,
 18838,
 14748,
 22941,
 37278,
 10655,
 2468,
 12709,
 35242,
 16811,
 8621,
 45487,
 39345,
 12721,
 45496,
 47545,
 8632,
 41405,
 37311,
 29119,
 25026,
 39363,
 18884,
 35275,
 35277,
 33234,
 468,
 39390,
 12766,
 6624,
 33250,
 4579,
 29159,
 8679,
 35305,
 12778,
 18925,
 25072,
 12784,
 29174,
 14840,
 10745,
 37370,
 23038,
 25087,
 27134,
 49665,
 8706,
 2561,
 2565,
 41477,
 20999,
 37386,
 16907,
 43531,
 27147,
 18961,
 25109,
 39446,
 33303,
 21013,
 45595,
 21020,
 10782,
 41504,
 14882,
 39460,
 6692,
 49702,
 37414,
 31277,
 4654,
 49711,
 39473,
 4659,
 2612,
 35383,
 21051,
 10814,
 25150,
 29248,
 35393,
 6723,
 47688,
 33354,
 19018,
 19020,
 41551,
 27217,
 33362,
 6738,
 23126,
 6744,
 39518,
 4709,
 615,
 8808,
 17004,
 19052,
 29292,
 37489,
 4721,
 33399,
 37501,
 10880,
 2691,
 27269,
 29317,
 47750,
 23174,
 23177,
 8842,
 17035,
 8844,
 47757,
 47756,
 27279,
 10891,
 33418,
 31372,
 25233,
 19092,
 35477,
 23182,
 25240,
 17049,
 25242,
 45722,
 49820,
 49821,
 37528,
 8861,
 8868,
 49833,
 43691,
 6830,
 45742,
 31409,
 12979,
 21178,
 6843,
 43707,
 41658,
 12987,
 21184,
 707,
 709,
 39625,
 31435,
 27340,
 49870,
 47823,
 17102,
 8913,
 39634,
 25299,
 2772,
 25301,
 2773,
 4822,
 15058,
 29401,
 25309,
 23267,
 15076,
 35557,
 27368,
 47851,
 29419,
 41709,
 10988,
 2802,
 29426,
 754,
 37621,
 10998,
 33527,
 11000,
 37625,
 35577,
 45819,
 13059,
 27396,
 31491,
 17163,
 29452,
 31500,
 39694,
 31505,
 21265,
 41748,
 43800,
 6943,
 43808,
 4895,
 43810,
 31521,
 11044,
 13093,
 806,
 39719,
 47912,
 6946,
 801,
 47913,
 19245,
 37685,
 15158,
 29495,
 17212,
 25404,
 47938,
 835,
 33602,
 9026,
 17225,
 4938,
 11083,
 31568,
 41810,
 47954,
 37716,
 33623,
 45917,
 39778,
 31587,
 41829,
 45926,
 37735,
 45928,
 9065,
 17259,
 47980,
 33645,
 13167,
 7026,
 27508,
 29557,
 2934,
 27511,
 31520,
 21371,
 47996,
 893,
 43904,
 15233,
 25473,
 4995,
 7047,
 48007,
 11146,
 45962,
 27532,
 2957,
 31634,
 19347,
 39828,
 48018,
 5016,
 48032,
 27556,
 41893,
 37799,
 7080,
 23464,
 27561,
 5035,
 11179,
 41901,
 23472,
 19377,
 23474,
 21424,
 948,
 25524,
 41911,
 23479,
 43961,
 9148,
 29631,
 21440,
 13251,
 27592,
 11209,
 39880,
 3017,
 46030,
 35790,
 11222,
 46039,
 48087,
 29658,
 15330,
 5090,
 39908,
 23523,
 31723,
 5100,
 9198,
 15350,
 25591,
 15352,
 11258,
 48124,
 19454,
 29694,
 31749,
 29703,
 23559,
 33800,
 3081,
 17424,
 1042,
 48150,
 44055,
 35869,
 23581,
 31775,
 9246,
 39969,
 3106,
 31779,
 27684,
 9251,
 35880,
 35883,
 48172,
 9261,
 33838,
 29742,
 21554,
 17458,
 9272,
 31802,
 25661,
 7230,
 37953,
 33857,
 27718,
 19527,
 1096,
 23627,
 21581,
 5201,
 11349,
 31833,
 17498,
 11355,
 19547,
 3172,
 46181,
 21606,
 25704,
 29806,
 23663,
 25717,
 5239,
 1149,
 19588,
 13447,
 7304,
 33929,
 35981,
 42130,
 15510,
 40088,
 44185,
 40093,
 25760,
 23715,
 3237,
 42149,
 36007,
 27816,
 9385,
 38060,
 33967,
 48305,
 3250,
 15541,
 15549,
 23744,
 46272,
 25796,
 11461,
 40139,
 27851,
 29901,
 38094,
 40143,
 42192,
 3282,
 3285,
 31961,
 48346,
 15578,
 34014,
 29925,
 3303,
 34026,
 27883,
 25838,
 15599,
 11504,
 5361,
 27895,
 17656,
 44284,
 21756,
 25853,
 42239,
 44288,
 17665,
 42241,
 19714,
 11516,
 34053,
 21761,
 21769,
 29963,
 19728,
 1298,
 32022,
 1303,
 3353,
 36122,
 17692,
 44318,
 36127,
 15648,
 5409,
 11554,
 23843,
 5411,
 19748,
 21795,
 38185,
 40235,
 23852,
 17710,
 46384,
 34097,
 34098,
 38196,
 9527,
 11577,
 34108,
 27965,
 7486,
 48447,
 44355,
 38214,
 42312,
 19787,
 23888,
 25937,
 21848,
 11612,
 1372,
 11617,
 23906,
 19810,
 15716,
 9577,
 44397,
 30061,
 40305,
 38258,
 19826,
 7543,
 34170,
 11646,
 23938,
 15751,
 44425,
 40331,
 11659,
 34187,
 28046,
 25998,
 40336,
 46486,
 1434,
 32157,
 40350,
 19871,
 38304,
 48545,
 44445,
 46499,
 15779,
 46504,
 23977,
 46506,
 7594,
 9643,
 1454,
 17842,
 7606,
 21943,
 26038,
 11702,
 34230,
 46523,
 21947,
 46525,
 23998,
 5571,
 21957,
 11718,
 3525,
 34245,
 30153,
 40394,
 46540,
 9676,
 5585,
 48595,
 7639,
 3545,
 42460,
 15838,
 30179,
 40421,
 48615,
 7655,
 44520,
 34282,
 46571,
 38377,
 28141,
 46574,
 44533,
 24054,
 36341,
 19958,
 13818,
 34301,
 32253,
 17921,
 11779,
 36356,
 5639,
 15882,
 24075,
 44559,
 15889,
 40466,
 13849,
 7707,
 3613,
 15902,
 34336,
 7713,
 3623,
 11820,
 13869,
 26159,
 22065,
 30260,
 42551,
 15928,
 48699,
 20028,
 46653,
 17983,
 5696,
 34369,
 1603,
 9796,
 48710,
 38470,
 32329,
 26185,
 7753,
 5709,
 44625,
 48721,
 5715,
 20054,
 11863,
 20057,
 44639,
 30310,
 44646,
 34408,
 13929,
 18025,
 9835,
 46703,
 18034,
 24180,
 22133,
 7801,
 44668,
 40574,
 24192,
 36482,
 18050,
 13955,
 22149,
 11911,
 9863,
 38539,
 22155,
 26253,
 5774,
 3727,
 32403,
 18069,
 11928,
 16027,
 30363,
 1693,
 48798,
 20125,
 42653,
 7840,
 30370,
 46760,
 28329,
 32426,
 36532,
 40635,
 1723,
 11963,
 5821,
 7877,
 38598,
 40651,
 3788,
 18124,
 46799,
 40657,
 18130,
 42709,
 7894,
 38615,
 26328,
 38619,
 44768,
 18145,
 32487,
 38633,
 34539,
 22252,
 48879,
 38640,
 16113,
 5874,
 44787,
 46836,
 9968,
 44792,
 22265,
 34555,
 22269,
 34559,
 22272,
 30465,
 24322,
 5891,
 1796,
 30469,
 34565,
 34566,
 20256,
 10017,
 28451,
 32547,
 40742,
 48936,
 42793,
 22315,
 40747,
 28462,
 28463,
 24366,
 14126,
 36658,
 42814,
 16190,
 42817,
 22339,
 22341,
 20294,
 24396,
 8016,
 36689,
 34650,
 20318,
 16223,
 32608,
 32613,
 48998,
 16233,
 20330,
 16234,
 32620,
 34670,
 3951,
 34675,
 3960,
 34682,
 28539,
 44924,
 1915,
 18306,
 10118,
 36743,
 24456,
 18313,
 3978,
 44938,
 12174,
 32655,
 36752,
 20371,
 18324,
 10133,
 34709,
 8086,
 20376,
 36761,
 8091,
 20383,
 47008,
 24481,
 10146,
 49062,
 40871,
 10151,
 36774,
 18346,
 14250,
 34728,
 14257,
 10165,
 34741,
 40887,
 12213,
 18361,
 40890,
 34750,
 16321,
 49092,
 28615,
 38856,
 8136,
 47050,
 24523,
 47051,
 14285,
 49102,
 38860,
 14284,
 45002,
 22488,
 18397,
 15054,
 24546,
 14307,
 8164,
 47081,
 34793,
 14315,
 40942,
 20475,
 22525]